### ISSUE TITLE
Launching more Traefik+Odoo+Postgresql Containers

### ISSUE THREAD

**Issue by axelpina** [paraita/docker-compose-traefik-odoo-postgres#5]
I ran the `docker-compose.yml` on a folder which we'll call `test1`. It ran perfectly fine with its certificate, traefik, odoo etc.

When I create a folder outside of `test1`, lets say `test2` & pull this repository to run Odoo, I change the following:

```   
ports:
      - "8069:8069"
      - "8072:8072"
```

to:

```   
ports:
      - "8070:8069"
      - "8072:8072"
```

I'd like some clarification as to how I need to do it.

Thanks in advance!

**Edit:**

- Have tried removing the `ports:` section from the `docker-compose` and re-running the `.yml`
- Tried upping the ports being used by the container (e.g: `8070:8069`, `8071:8069`)
- Tried cloning the repository in a separate folder and reunning the `.yml` with different `.env` credentials

**Comment by axelpina** [comment]
Managed to solve my issue! Will be sharing my findings soon!

**Comment by matnoublanche** [comment]
Hi @AxelPina,

I'm actually in the same situation as you, is it possible to explain how you did it ?

Thank's !

**Comment by matnoublanche** [comment]
I respond to myself, I didn't see your repository.

Found it now :)

https://github.com/AxelPina/docker-compose-traefik-odoo-postgres/blob/master/docker-compose.yml
